[window]
opacity = 0.9

[window.dimensions]
columns = 180
lines = 54

[window.position]
x = 32
y = 18

[window.padding]
x = 5
y = 5

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
size = 13

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key  = "F"                     # the physical F key
mods = "Alt|Shift"             # press Alt + Shift together
action = "ToggleFullscreen"
